server:
  port: 4003
my:
  greeting: Hello
  list:
    values: one,two,three
keyValues: "{str:'val1', 'str2': 'val2'}"
db:
  url: http://profile-test.com
  username: usertest
  password: passtest
  port: 6001